config/routes.rb
Rails.application.routes.draw do
  root to: 'static#home'
  get 'home', to: 'static#home'
  # get '/portfolio', to: 'static#portfolio'
  get '/mentions_legales', to: 'static#mentions_legales'
  post '/mail', to: 'mailer#contact_email'
  namespace :admin do
    root to: 'admin#dashboard'
    devise_for :admins
    resources :contents, only: [:update, :edit]
    resources :folios, except: [:index, :show] do
      resources :capture, only: [:create]
    end
    put '/folios/:id/order_up', to: 'folios#order_up', as: 'folios_order_up'
    put '/folios/:id/order_down', to: 'folios#order_down', as: 'folios_order_down'
    resources :cv_entries, except: [:index, :show]
    resources :time_cvs, except: [:index, :show]
    put '/cv_time/:id/order_up', to: 'time_cvs#order_up', as: 'time_cv_order_up'
    put '/cv_time/:id/order_down', to: 'time_cvs#order_down', as: 'time_cv_order_down'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/time_cv.rb
class TimeCv < ApplicationRecord
  validates :date,
    presence: true,
    uniqueness: true
  validates :order,
    presence: true
  has_many :entries, foreign_key: 'date', class_name: 'CvEntry', dependent: :destroy

  before_validation :set_new_order, on: :create
  after_destroy :reorder_after_destroy

  def set_new_order
    self.order ||= TimeCv.count
  end

  def first_place?
    self.order == 0
  end

  def last_place?
    self.order == TimeCv.count - 1
  end

  def reorder_after_destroy
    TimeCv.all.each do |time|
      new_order = time.order - 1
      if time.order > self.order
        time.update(order: new_order)
      end
    end
  end
end

app/controllers/admin/time_cvs_controller.rb
class Admin::TimeCvsController < ApplicationController

  before_action :authenticate_admin_admin!

  def new
    respond_to do |format|
      format.js { }
    end
  end

  def create
    time_cv = TimeCv.new(date: params[:date])
    if time_cv.save
      flash[:alert] = nil
      @time = time_cv
      @valid = true
    else
      flash[:alert] = 'Erreur'
    end
    respond_to do |format|
      format.js {}
    end
  end

  def edit
    @time = TimeCv.find(params[:id])
    respond_to do |format|
      format.js {}
    end
  end

  def update
    @time = TimeCv.find(params[:id])
    update = params.permit(:date)
    if @time.update(update)
      @valid = true
    else
      flash[:alert] = 'Error'
    end
    respond_to do |format|
      format.js {}
    end
  end

  def destroy
    @time = TimeCv.find(params[:id])
    @time.destroy
    respond_to do |format|
      format.js {}
    end
  end

  def order_up
    @time = TimeCv.find(params[:id])
    unless @time.first_place?
      @valid = @time.order
      TimeCv.where(order: @time.order - 1).update(order: @time.order)
      @time.update(order: @time.order - 1)
    end
    respond_to do |format|
      format.js {}
    end
  end

  def order_down
    @time = TimeCv.find(params[:id])
    unless @time.last_place?
      @valid = @time.order
      TimeCv.where(order: @time.order + 1).update(order: @time.order)
      @time.update(order: @time.order + 1)
    end
    respond_to do |format|
      format.js {}
    end
  end

end

app/helpers/admin/time_cvs_helper.rb
module Admin::TimeCvsHelper
end

app/views/admin/time_cvs/_modal.html.erb
<div class="modal fade bd-example-modal-lg" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">

        <%= form_tag(admin_time_cvs_path, method:'post', remote: true) do %>
          <div class='form-group'>
            <%= text_field_tag 'date', nil, placeholder: 'Nouvelle période', class: 'form-control', autofocus: true %>
          </div>
          <button id='quit_modal' type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">annuler</button>
          <%= submit_tag 'ajouter', class: 'btn btn-sm btn-success' %>
        <% end %>
        
      </div>
    </div>
  </div>
</div>

app/views/admin/time_cvs/_modal_edit.html.erb
<div class="modal fade bd-example-modal-lg" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">

        <%= form_tag(admin_time_cv_path(id: time.id), method:'put', remote: true) do %>
          <div class='form-group'>
            <%= text_field_tag 'date', time.date, class: 'form-control', focus: true %>
          </div>
          <button id='quit_modal' type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">annuler</button>
          <a href=<%= admin_time_cv_path(id: time.id) %> data-method='delete' data-remote='true' data-confirm='Supprimer ?' type="button" class="btn btn-sm btn-danger">supprimer</a>
          <%= submit_tag 'modifier', class: 'btn btn-sm btn-success' %>
        <% end %>
        
      </div>
    </div>
  </div>
</div>

app/views/admin/time_cvs/_modal_new.html.erb
<div class="modal fade bd-example-modal-lg" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">

        <%= form_tag(admin_time_cvs_path, method:'post', remote: true) do %>
          <div class='form-group'>
            <%= text_field_tag 'date', nil, placeholder: 'Nouvelle période', class: 'form-control', autofocus: true %>
          </div>
          <button id='quit_modal' type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">annuler</button>
          <%= submit_tag 'ajouter', class: 'btn btn-sm btn-success' %>
        <% end %>
        
      </div>
    </div>
  </div>
</div>

app/views/admin/time_cvs/_new_date.html.erb
<div class='date date-<%= time.id %> mb-3'>
    <div class='row'>
        <div class='col-lg-6'>
          <h2 class='m-0 mt-1 mb-lg-0 mb-3'><%= time.date %></h2>
        </div>
        <div class='col-lg-6 text-lg-right'>
          <p class='m-0'>
            <a href=<%= edit_admin_time_cv_path(id: time.id) %> class='btn btn-danger mb-4 d-lg-none d-inline mr-3 sup' data-remote='true'>modifier</a><!-- modal -->
            <a href=<%= new_admin_cv_entry_path(date: time.id) %> data-remote='true' class='btn btn-primary mb-4 d-lg-none d-inline'>ajouter une entrée</a><!-- modal -->
          </p> 
        </div>
    </div>
    <hr class=''>
    <div class='row mb-3'>
      <div class='col-11 mb-3' id='entries-<%= time.id %>'>

      <% time.entries.each do |entry| %>
    
          <div class='entry mb-3 entry-<%= entry.id %>'>
            <div class='d-flex'>
              <h3 class='m-0'><%= entry.title %></h3>
              <p class='m-0'><a href=<%= edit_admin_cv_entry_path(id: entry.id) %> data-remote='true' class='btn btn-danger btn-sm ml-3 mb-0 d-lg-none d-inline'>Modifier</a></p> <!-- modal -->
            </div>
            <% if !entry.sub.nil? %>
              <p class='m-0'><small><%= entry.sub %></small></p>
            <% end %>
          </div>

        <% end %>
    
      </div>
      <div class='col-lg-1'>
        <p><a href=<%= admin_time_cv_order_up_path(id: time.id) %> data-method='put' data-remote='true' class='btn btn-secondary d-lg-none d-inline'>&#9650;</a></p>
        <p><a href=<%= admin_time_cv_order_down_path(id: time.id) %> data-method='put' data-remote='true' class='btn btn-secondary d-lg-none d-inline'>&#9660;</a></p>
      </div>
    </div>
  </div>

app/views/admin/time_cvs/create.js.erb
<% if @valid == true %>
  $('#cv_entries').append("<%= j render 'new_date', time: @time %>");
  quitModal();
<% else %>
  $('.alert').remove();
  $('.modal-body').prepend("<%= j render 'flash_new' %>");
<% end %>

app/views/admin/time_cvs/destroy.js.erb
$('.date-<%= @time.id %>').remove();
quitModal();

app/views/admin/time_cvs/edit.js.erb
$('.container').after("<%= j render 'modal_edit', time: @time %>");
$('#modal').modal('toggle');

quitModalBtn();

app/views/admin/time_cvs/order_down.js.erb
<% if @valid %>
  $('#cv_entries').children()[<%= @valid %>].before($('#cv_entries').children()[<%= @valid + 1 %>]);
<% end %>

app/views/admin/time_cvs/order_up.js.erb
<% if @valid %>
  $('#cv_entries').children()[<%= @valid %>].after($('#cv_entries').children()[<%= @valid - 1 %>]);
<% end %>

app/views/admin/time_cvs/update.js.erb
<% if @valid == true %>
  $('.date-<%= @time.id %> h2').html("<%= @time.date %>");
  quitModal();
<% else %>
  $('.alert').remove();
  $('.modal-body').prepend("<%= j render 'flash_new' %>");
<% end %>