config/routes.rb
Rails.application.routes.draw do
  root to: 'static#home'
  get 'home', to: 'static#home'
  # get '/portfolio', to: 'static#portfolio'
  get '/mentions_legales', to: 'static#mentions_legales'
  post '/mail', to: 'mailer#contact_email'
  namespace :admin do
    root to: 'admin#dashboard'
    devise_for :admins
    resources :contents, only: [:update, :edit]
    resources :folios, except: [:index, :show] do
      resources :capture, only: [:create]
    end
    put '/folios/:id/order_up', to: 'folios#order_up', as: 'folios_order_up'
    put '/folios/:id/order_down', to: 'folios#order_down', as: 'folios_order_down'
    resources :cv_entries, except: [:index, :show]
    resources :time_cvs, except: [:index, :show]
    put '/cv_time/:id/order_up', to: 'time_cvs#order_up', as: 'time_cv_order_up'
    put '/cv_time/:id/order_down', to: 'time_cvs#order_down', as: 'time_cv_order_down'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cv_entry.rb
class CvEntry < ApplicationRecord
  validates :title,
    presence: true,
    uniqueness: true
  belongs_to :date, class_name: 'TimeCv'
end

app/controllers/admin/cv_entries_controller.rb
class Admin::CvEntriesController < ApplicationController

  before_action :authenticate_admin_admin!

  def new
    @date = params[:date]
    respond_to do |format|
      format.js {}
    end
  end

  def create
    @date = TimeCv.find(params[:date])
    entry = CvEntry.new(title: params[:title], sub: params[:sub], date: @date)
    if entry.save
      flash[:alert] = nil
      @entry = entry
      @valid = true
    else
      flash[:alert] = 'Erreur'
    end
    respond_to do |format|
      format.js {}
    end
  end

  def edit
    @entry = CvEntry.find(params[:id])
    respond_to do |format|
      format.js {}
    end
  end

  def update
    @entry = CvEntry.find(params[:id])
    update = params.permit(:title, :sub)
    if @entry.update(update)
      @valid = true
    else
      flash[:alert] = 'Error'
    end
    respond_to do |format|
      format.js {}
    end
  end

  def destroy
    @entry = CvEntry.find(params[:id])
    @entry.destroy
    respond_to do |format|
      format.js {}
    end
  end

end

app/helpers/admin/cv_entries_helper.rb
module Admin::CvEntriesHelper
end

app/views/admin/cv_entries/_modal_edit.html.erb
<div class="modal fade bd-example-modal-lg" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">

        <%= form_tag(admin_cv_entry_path(id: entry.id), method:'put', remote: true) do %>
          <div class='form-group'>
            <%= text_field_tag 'title', entry.title, class: 'form-control', focus: true %>
          </div>
          <div class='form-group'>
            <%= text_field_tag 'sub', entry.sub, placeholder: 'Description ?', class: 'form-control', focus: true %>
          </div>
          <button id='quit_modal' type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">annuler</button>
          <a href=<%= admin_cv_entry_path(id: entry.id) %> data-method='delete' data-remote='true' data-confirm='Supprimer ?' type="button" class="btn btn-sm btn-danger">supprimer</a>
          <%= submit_tag 'modifier', class: 'btn btn-sm btn-success' %>
        <% end %>
        
      </div>
    </div>
  </div>
</div>

app/views/admin/cv_entries/_modal_new.html.erb
<div class="modal fade bd-example-modal-lg" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">

        <%= form_tag(admin_cv_entries_path, method:'post', remote: true) do %>
            <%= hidden_field_tag 'date', date %>
          <div class='form-group'>
            <%= text_field_tag 'title', nil, placeholder: 'Titre', class: 'form-control', autofocus: true %>
          </div>
          <div class='form-group'>
            <%= text_field_tag 'sub', nil, placeholder: 'Description ?', class: 'form-control', autofocus: true %>
          </div>
          <button id='quit_modal' type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">annuler</button>
          <%= submit_tag 'ajouter', class: 'btn btn-sm btn-success' %>
        <% end %>
        
      </div>
    </div>
  </div>
</div>

app/views/admin/cv_entries/_new_entry.html.erb
<div class='entry mb-3 entry-<%= entry.id %>'>
  <div class='d-flex'>
    <h3 class='m-0'><%= entry.title %></h3>
    <p class='m-0'><a href=<%= edit_admin_cv_entry_path(id: entry.id) %> data-remote='true' class='btn btn-danger btn-sm ml-3 mb-0 d-lg-none d-inline'>Modifier</a></p> <!-- modal -->
  </div>
  <% if !entry.sub.nil? %>
    <p class='m-0'><small><%= entry.sub %></small></p>
  <% end %>
</div>

app/views/admin/cv_entries/create.js.erb
<% if @valid == true %>
  $('#entries-<%= @entry.date.id %>').append("<%= j render 'new_entry', entry: @entry %>");
  quitModal();
<% else %>
  $('.alert').remove();
  $('.modal-body').prepend("<%= j render 'flash_new' %>");
<% end %>

app/views/admin/cv_entries/destroy.js.erb
$('.entry-<%= @entry.id %>').remove();
quitModal();

app/views/admin/cv_entries/edit.js.erb
$('.container').after("<%= j render 'modal_edit', entry: @entry %>");
$('#modal').modal('toggle');

quitModalBtn();

app/views/admin/cv_entries/new.js.erb
$('.container').after("<%= j render 'modal_new', date: @date %>");
$('#modal').modal('toggle');

quitModalBtn();

app/views/admin/cv_entries/update.js.erb
<% if @valid == true %>
  $('.entry-<%= @entry.id %> h3').html("<%= @entry.title %>");
  <% if !@entry.sub.nil? && @entry.sub != "" %>
    $('.entry-<%= @entry.id %> > p').remove();
    $('.entry-<%= @entry.id %> .d-flex').after("<p class='m-0'><small><%= @entry.sub %></small></p>");
  <% else %>
    $('.entry-<%= @entry.id %> > p').remove();
  <% end %>
  quitModal();
<% else %>
  $('.alert').remove();
  $('.modal-body').prepend("<%= j render 'flash_new' %>");
<% end %>