config/routes.rb
Rails.application.routes.draw do
  root to: 'static#home'
  get 'home', to: 'static#home'
  # get '/portfolio', to: 'static#portfolio'
  get '/mentions_legales', to: 'static#mentions_legales'
  post '/mail', to: 'mailer#contact_email'
  namespace :admin do
    root to: 'admin#dashboard'
    devise_for :admins
    resources :contents, only: [:update, :edit]
    resources :folios, except: [:index, :show] do
      resources :capture, only: [:create]
    end
    put '/folios/:id/order_up', to: 'folios#order_up', as: 'folios_order_up'
    put '/folios/:id/order_down', to: 'folios#order_down', as: 'folios_order_down'
    resources :cv_entries, except: [:index, :show]
    resources :time_cvs, except: [:index, :show]
    put '/cv_time/:id/order_up', to: 'time_cvs#order_up', as: 'time_cv_order_up'
    put '/cv_time/:id/order_down', to: 'time_cvs#order_down', as: 'time_cv_order_down'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/admin/_content.html.erb
<% @contents.each do |content| %>

  <div class='row content mt-3'>
    <div class='col-lg-2 text-lg-right'>
      <h3 class='pt-4 m-2 text-dark'><%= content.name %></h3>
      <a href=<%= edit_admin_content_path(id: content.id) %> class='btn btn-sm btn-danger d-lg-none d-inline mr-1' data-remote='true'>modifier</a> <!-- launches modal -->
    </div>
    <div class='col-lg-10 mt-lg-0 mt-4'>
      <div class='card p-4'>
        <% if !content.title.nil? %>
          <h4 class='text-dark'><%= content.title %></h4>
        <% end %>
        <p class='m-0 text-secondary'><%= content.body %></p>
      </div>
    </div>
  </div>

<% end %>

app/views/admin/admin/_cv.html.erb
<p><a href=<%= new_admin_time_cv_path %> class='btn btn-primary mb-4' data-remote='true'>ajouter une date</a></p> <!-- modal -->
<div id='cv_entries'>
  
  <% @times.each do |time| %>
  
  <div class='date date-<%= time.id %> mb-3'>
    <div class='row'>
        <div class='col-lg-6'>
          <h2 class='m-0 mt-1 mb-lg-0 mb-3'><%= time.date %></h2>
        </div>
        <div class='col-lg-6 text-lg-right'>
          <p class='m-0'>
            <a href=<%= edit_admin_time_cv_path(id: time.id) %> class='btn btn-danger mb-4 d-lg-none d-inline mr-3 sup' data-remote='true'>modifier</a><!-- modal -->
            <a href=<%= new_admin_cv_entry_path(date: time.id) %> data-remote='true' class='btn btn-primary mb-4 d-lg-none d-inline'>ajouter une entrée</a><!-- modal -->
          </p> 
        </div>
    </div>
    <hr class=''>
    <div class='row mb-3'>
      <div class='col-11 mb-3' id='entries-<%= time.id %>'>

      <% time.entries.each do |entry| %>
    
          <div class='entry mb-3 entry-<%= entry.id %>'>
            <div class='d-flex'>
              <h3 class='m-0'><%= entry.title %></h3>
              <p class='m-0'><a href=<%= edit_admin_cv_entry_path(id: entry.id) %> data-remote='true' class='btn btn-danger btn-sm ml-3 mb-0 d-lg-none d-inline'>Modifier</a></p> <!-- modal -->
            </div>
            <% if !entry.sub.nil? %>
              <p class='m-0'><small><%= entry.sub %></small></p>
            <% end %>
          </div>

         <% end %>

      </div>
      <div class='col-lg-1'>
        <p><a href=<%= admin_time_cv_order_up_path(id: time.id) %> data-method='put' data-remote='true' class='btn btn-secondary d-lg-none d-inline'>&#9650;</a></p>
        <p><a href=<%= admin_time_cv_order_down_path(id: time.id) %> data-method='put' data-remote='true' class='btn btn-secondary d-lg-none d-inline'>&#9660;</a></p>
      </div>
    </div>
  </div>
  
  <% end %>
</div>

app/views/admin/admin/_folio.html.erb
<p><a href=<%= new_admin_folio_path %> data-remote='true' class='btn btn-primary mb-4'>Ajouter un projet</a></p> <!-- modal -->
<div id='folios'>
  
  <% @folios.each do |folio| %>
  
    <div>
      <div class='folio row mt-4'>
        <div class="col-lg-4 text-right capture-<%= folio.id %> d-flex flex-column">
          <%= image_tag(folio.capture, class: 'mb-4 rounded capture order-lg-1 order-2') %>
          <p class='d-inline order-lg-2 order-1'><a href=<%= edit_admin_folio_path(id: folio.id) %> data-remote='true' class='btn btn-sm btn-danger d-lg-none d-inline'>modifier</a></p><!-- modal -->
        </div>
        <div class='col-lg-7 mt-lg-0 mt-3'>
          <div class="card w-100 px-sm-5 px-2">
            <div class="row">
                <div class="card-body folio-<%= folio.id %>">
                  <h4 class="card-title"><%= folio.title %></h4>
                  <p><a href=<%= folio.website %>><small class="card-text"><%= folio.website %></small></a></p>
                  <p class="card-text text-secondary desc"><%= folio.description %></p>
                  <p><small class="card-text sm1"><%= folio.description_mini %></small></p>
                  <p><small class="card-text sm2"><%= folio.techs %></small></p>
                  <p><small class="card-text sm3"><%= folio.work %></small></p>
                </div>
            </div>
          </div>
        </div>
        <div class='col-lg-1 align-center pt-lg-5 pt-4'>
          <p><a href=<%= admin_folios_order_up_path(id: folio.id) %> data-remote='true' data-method='put' class='btn btn-secondary d-lg-none d-inline'>&#9650;</a></p>
          <p><a href=<%= admin_folios_order_down_path(id: folio.id) %> data-remote='true' data-method='put' class='btn btn-secondary d-lg-none d-inline'>&#9660;</a></p>
        </div>
      </div>
      <hr>
    </div>
  
  <% end %>
  
</div>

app/views/admin/admin/dashboard.html.erb
<header>
  <%= render 'layouts/admin/navbar' %>
</header>

<div class='container'>
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active text-dark" id="home-tab" data-toggle="tab" href="#contents" role="tab" aria-controls="contents" aria-selected="true">contents</a>
    </li>
    <li class="nav-item">
      <a class="nav-link text-dark" id="portfolio-tab" data-toggle="tab" href="#portfolio" role="tab" aria-controls="portfolio" aria-selected="false">portfolio</a>
    </li>
    <li class="nav-item">
      <a class="nav-link text-dark" id="cv-tab" data-toggle="tab" href="#cv" role="tab" aria-controls="cv" aria-selected="false">cv</a>
    </li>
  </ul>
  <div class="tab-content mb-5" id="myTabContent">
    <div class="tab-pane fade show active pt-5" id="contents" role="tabpanel" aria-labelledby="contents-tab">
    
    <%= render 'content' %>

    </div>
    <div class="tab-pane fade pt-5 mb-5" id="portfolio" role="tabpanel" aria-labelledby="portfolio-tab">
    
    <%= render 'folio' %>

    </div>
    <div class="tab-pane fade pt-5 mb-5" id="cv" role="tabpanel" aria-labelledby="cv-tab">
    
    <%= render 'cv' %>

    </div>
  </div>
</div>